### ISSUE TITLE
backend requests employee side

### ISSUE THREAD

**Issue by keeswie** [keeswie/PTSD#10]
## Tasks
 - make schemas
 - make working backend requests for each endpoint

## DoD (Definition of Done)
 - [x] working schemas (required, validation, etc)
 - [x] Post /employee
 - [x] Get /employee
 - [x] Get /employee/{id}
 - [x] Put employee/{id}
 - [x] Delete /employee/{id}
 - [x] Post /product
 - [x]  Get /product/{barcode}
 - [x]  Put /product/{barcode}/at/{location}
 - [x]  Delete /product/{barcode}/at/{location}
 - [x] Post /location
 - [x]  Delete /location/at/{barcode}
 - [x]  Get /location/at/{barcode}
 - [x]  Put /location/{barcode}
