### ISSUE TITLE
front end employee

### ISSUE THREAD

**Issue by keeswie** [keeswie/PTSD#14]
## Tasks
- get all products
 - change which product a location holds by giving location barcode and product barcode
- updating the number of products at a location
- checking all locations and see if the products are within boundaries
-connect to given API
- create supply order

## DoD (Definition of Done)
 - [ ] get put product/ location
 - [ ] connect to given API
 - [ ] supply order maker
